---
- name: Simple echo test
  hosts: ExampleTarget
  gather_facts: no

  # Role are always executed before the tasks
  roles: 
    - hello-world

  tasks:
    - name: Testing local echo
      local_action:
        module: debug
        msg: Hello world from the local machine

    - name: Testing echo
      debug:
        msg: Hello World from the target machine
